# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
description: "Deploy static Website to GitHub Pages"
inputs:
  username:
    required: true
    description: "UserName"
  email:
    required: true
    description: "Email"
  GITHUB_TOKEN:
    default: true
    required: false
    description: "Token"
    
runs:
  using: "composite" 
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        npm install
      shell: bash

    - name: Test the App
      run: |
        npm test
      shell: bash

    - name: Build
      run: |
        npm run build
      shell: bash

    - name: Configure Git
      run: |
        git config --local user.name ${{ inputs.username }}
        git config --local user.email ${{ inputs.email }}
      shell: bash

    - name: Deploy
      run: |
        npm run deploy --token=${{ inputs.GITHUB_TOKEN }}
      shell: bash
