# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
description: "Deploy static Website to GitHub Pages"
inputs:
  username:
    required: true
    description: "UserName"
  email:
    required: true
    description: "Email"
  GITHUB_TOKEN:
    required: false
    description: "Token"
  updateDescription:
    default: true
    required: false
    description: "Update Repository description with url to website"
    
runs:
  using: "composite" 
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        npm install
      shell: bash

    - name: Test the App
      run: |
        npm test
      shell: bash

    - name: Build
      run: |
        npm run build
      shell: bash

    - name: Configure Git
      run: |
        git config --local user.name ${{ inputs.username }}
        git config --local user.email ${{ inputs.email }}
      shell: bash

    - name: Deploy
      run: |
        npm run deploy --token=${{ inputs.GITHUB_TOKEN }}
      shell: bash

    - name: Update repository description
      if: ${{ inputs.updateDescription == 'true' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{inputs.GITHUB_TOKEN}}
        script: |
          const repo = context.repo;
          const url = `https://${repo.owner}.github.io/${repo.repo}/`;
          github.rest.repos.update({
            owner: repo.owner,
            repo: repo.repo,
            homepage: `${url}`
          });
