name: Deploy static content to Pages
description: "Deploy static Website to GitHub Pages"
inputs:
  repo_name:
    required: true
    description: "Repo Name"
  token:
    required: true
    description: "Github token"
  
runs:
  using: "docker"
  image: "Dockerfile"
  env: 
    GITHUB_TOKEN: ${{ inputs.token }}
    REPO: ${{ inputs.repo_name }}
